
import os
import re
user=str(os.getcwd())
file= open(f'{user}/external/bin/activate','r')
read1=file.read()
read1=re.sub('VIRTUAL_ENV=.*',f'VIRTUAL_ENV=\"{user}/external\"',read1)
file.close()
file= open(f'{user}/external/bin/activate','w')
file.write(read1)
file.close()

f1=open('main.desktop','w').close()
f1=open('main.desktop','a')
f1.write('#!/usr/bin/env xdg-open')
f1.write('\n')
f1.write('[Desktop Entry]')
f1.write('\n')
f1.write('Type=Application')
f1.write('\n')
f1.write('Version=2.0')
f1.write('\n')
f1.write('Name=Lib Analyzer')
f1.write('\n')
f1.write('Exec=bash chmod 777 filler.sh')
f1.write('\n')
f1.write(f'Exec=bash filler.sh')
f1.write('\n')
f1.write(f'Path={user}')
f1.write('\n')
f1.write(f'X-Icon-Path={user}/splash.png')
f1.write('\n')
f1.write(f'Icon={user}/splash.png')
f1.write('\n')
f1.write('Name[en_US]=Lib Analyzer')
f1.close()
print('ALL SPECIFICATIONS ARE DONE SUCCESSFULLY')

